# Generated by Django 5.2 on 2025-04-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='text',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
