# Generated by Django 5.2 on 2025-04-14 06:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('useful_links', models.CharField(blank=True, max_length=100)),
                ('information', models.CharField(blank=True, max_length=100)),
                ('facebook', models.TextField(blank=True)),
                ('twitter', models.TextField(blank=True)),
                ('linkedin', models.TextField(blank=True)),
                ('behance', models.TextField(blank=True)),
                ('footer', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
