# Generated by Django 5.2 on 2025-04-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_basic_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic',
            name='category',
        ),
        migrations.AddField(
            model_name='basic',
            name='about',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='basic',
            name='contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='basic',
            name='faq',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='basic',
            name='help',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='basic',
            name='help_info',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='basic',
            name='homepage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='basic',
            name='kids',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='basic',
            name='men',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='basic',
            name='shipping',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='basic',
            name='title_shopping',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='basic',
            name='tracking',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='basic',
            name='women',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='basic',
            name='information',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='basic',
            name='useful_links',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
